version: '3.8'

services:
  api:
    build: ./api
    container_name: clash_api
    restart: always
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: clash_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api