version: '3.8'

services:
  # API Node.js
  api:
    build: ./api
    container_name: clash_api
    restart: always
    expose:
      - "3000"
    env_file:
      - .env

  # Frontend Angular + NGINX
  frontend:
    build: ./frontend
    container_name: clash_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api